name: PlayerKillDropPlugin
version: 1.2-RELEASE
main: com.PlayerKillDrop.PlayerKillDropPlugin
api-version: 1.20
description: A Minecraft plugin that manages item drops based on death cause.
commands:
  togglekilldrop:
    description: Toggle the PlayerKillDropPlugin on or off.
    permission: killdrop.toggle
  reloadkilldrop:
    description: Reload the configuration for PlayerKillDropPlugin.
    permission: killdrop.reload
permissions:
  killdrop.toggle:
    description: Permission to toggle the plugin on or off.
    default: op
  killdrop.reload:
    description: Permission to reload the plugin configuration.
    default: op
